#!/usr/bin/env bash
set -e

if [ $EUID -ne 0 ]; then
  echo "[!] run as root."
  exit 1
fi

USERNAME="$1"

if [ -z $USERNAME ]; then
  echo "[!] usage: $0 <username>"
  exit 1
fi

if [[ -z $(command -v sudo) ]] ; then
  echo "[*] installing sudo..."
  apt install sudo -y
  echo "[+] sudo package installed..."
fi

adduser $USERNAME sudo
echo "[+] $USERNAME succesfully added to sudo group."

read -rp "[?] reboot now? (y/N): " reboot
if [ "$reboot" = "y" ]; then
  systemctl reboot
fi
