#!/usr/bin/env bash
set -e

if [ $EUID -ne 0 ]; then
  echo "[!] run as root."
  exit 1
fi

REAL_USER="${SUDO_USER:-$USER}"

if [[ -z $(command -v sudo) ]] ; then
  echo "[*] installing sudo..."
  apt install sudo -y
  echo "[+] sudo package installed..."
fi

adduser $REAL_USER sudo
echo "[+] $REAL_USER succesfully added to sudo group."

read -rp "[?] reboot now? (y/N): " reboot
if [ "$reboot" = "y" ]; then
  systemctl reboot
fi
